### ISSUE TITLE
Logo offer

### ISSUE THREAD

**Issue by familqasimov** [alvince/AvatarImageView#2]
Hi Alvince

I'm designing for open source projects and I'm trying to expand my design tecnigue with these jobs. I want to design an icon for your project. I have a few ideas in my mind, I hope you accept and I do them. Please let me know if you have any ideas. In this way, we create a logo that will make you happy.
If you want, you can look at my repositories.
https://github.com/familqasimov?tab=overview&from=2018-06-01&to=2018-06-30

Best regards.
Famil

**Comment by alvince** [comment]
Thank u, I am very happy that you can have this idea.
Of course, I accept your thoughts.

thx

**Comment by familqasimov** [comment]
![avatarimageview](https://user-images.githubusercontent.com/36432269/43642535-050bc394-9739-11e8-9381-b6e82bace3f0.png)

Best regard
Famil

**Comment by alvince** [comment]
Cool, thank u very much!
I like the first or them.

**Comment by familqasimov** [comment]
I think you will like even a little change.

![avatarimageview 2](https://user-images.githubusercontent.com/36432269/43689653-df309df2-990e-11e8-8ea6-4e8b1c441c2e.png)

**Comment by alvince** [comment]
The first one, I like simplicity.
The second's color is too dazzling.
What u think?

**Comment by familqasimov** [comment]
From the very beginning, the first logo is more attractive because it is the color of the day and night. But the text part of the second logo seems to me more interesting.

**Comment by alvince** [comment]
Yes,u r right
I like the text part of the second also
